services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "7777:7777"
    networks:
      - my-network
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-broker
    depends_on:
      - mqtt-broker
  temperature_sensor:
    build:
      context: ./sensors/temperature_sensor
      dockerfile: Dockerfile
    depends_on:
      - gateway
    networks:
      - my-network
  pressure_sensor:
    build:
      context: ./sensors/pressure_sensor
      dockerfile: Dockerfile
    depends_on:
      - gateway
    networks:
      - my-network
  heartrate_sensor:
    build:
      context: ./sensors/heartrate_sensor
      dockerfile: Dockerfile
    depends_on:
      - gateway
    networks:
      - my-network
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - my-network
  mqtt-subscriber:
    build:
      context: ./mqtt-subscriber
      dockerfile: Dockerfile
    depends_on:
      - mqtt-broker
    networks:
      - my-network
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_TOPICS=temperature,pressure,heartRate
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=healthdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: healthdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my-network
volumes:
  pgdata:
networks:
  my-network:
    driver: bridge