# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\x12\x0bsensor_data\"`\n\nSensorData\x12\x11\n\tsensor_id\x18\x01 \x01(\t\x12\x10\n\x08systolic\x18\x02 \x01(\x02\x12\x11\n\tdiastolic\x18\x03 \x01(\x02\x12\x0c\n\x04unit\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\"\x07\n\x05\x45mpty2L\n\rSensorService\x12;\n\x0cSendPressure\x12\x17.sensor_data.SensorData\x1a\x12.sensor_data.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORDATA']._serialized_start=29
  _globals['_SENSORDATA']._serialized_end=125
  _globals['_EMPTY']._serialized_start=127
  _globals['_EMPTY']._serialized_end=134
  _globals['_SENSORSERVICE']._serialized_start=136
  _globals['_SENSORSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
